apiVersion: apps/v1
kind: Deployment
metadata:
  name: halloween
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halloween
  template:
    metadata:
      labels:
        app: halloween
    spec:
      containers:
        - name: halloween
          image: DOCKERHUB_USERNAME/halloween-httpd:0.0.1
          ports:
            - containerPort: 80
